/// DEMO STAND-IN. The seed catalogue.
///
/// This file is the single place to change what the shop sells while you are
/// still on the in-memory backend. Every field below maps to something visible
/// on the site or in the structured data; the docs (`doc/index.html`) have a
/// field reference. Delete `lib/backend/` and implement the repository
/// interfaces in `lib/domain/` when you connect a real database.
library;

import '../domain/catalog/models/product.dart';

final DateTime _t = DateTime.utc(2026, 3, 1);

List<Category> seedCategories() => const [
  Category(
    slug: 'footwear',
    name: 'Footwear',
    headline: 'Sneakers made to be worn every day',
    description: 'Light, breathable and low-profile sneakers for the commute, the weekend and everything between.',
    image: ProductImage(base: 'sneaker-white', alt: 'A pair of white knit sneakers seen from above'),
  ),
  Category(
    slug: 'audio',
    name: 'Audio',
    headline: 'Headphones with honest sound',
    description: 'Wired and wireless headphones tuned for long listening sessions, without the marketing noise.',
    image: ProductImage(base: 'headphones-pink', alt: 'Silver headphones on a pink background'),
  ),
  Category(
    slug: 'accessories',
    name: 'Accessories',
    headline: 'Small things, carefully chosen',
    description: 'Watches and sunglasses with a quiet, durable design that goes with most things you own.',
    image: ProductImage(base: 'watch-classic', alt: 'A minimalist watch with a brown leather strap'),
  ),
  Category(
    slug: 'bags',
    name: 'Bags',
    headline: 'Carry it well',
    description: 'Leather and canvas bags built to be repaired rather than replaced: duffels, satchels and backpacks.',
    image: ProductImage(base: 'satchel', alt: 'Three leather satchels in tan and black'),
  ),
  Category(
    slug: 'home',
    name: 'Home & desk',
    headline: 'A calmer desk',
    description: 'Everyday desk and kitchen objects: a stoneware mug and a notebook that lies flat.',
    image: ProductImage(base: 'mug', alt: 'A plain white ceramic mug on a table'),
  ),
];

List<Product> seedProducts() => [
  Product(
    id: 'p_stride_knit',
    slug: 'stride-knit-sneaker',
    name: 'Stride Knit Sneaker',
    brand: 'Northgate',
    categorySlug: 'footwear',
    summary: 'A featherweight knit sneaker with a cushioned sole and a clean, logo-free upper.',
    description: [
      'The Stride is our lightest everyday sneaker. The upper is a single piece of recycled knit that breathes in summer and keeps its shape after a hundred washes.',
      'A cushioned foam midsole and a flexible rubber outsole make it comfortable from the first step, with no break-in period.',
    ],
    priceCents: 9800,
    compareAtCents: 12000,
    sku: 'NG-SNK-001',
    gtin: '8401234510006',
    variantLabel: 'Size (EU)',
    images: const [
      ProductImage(base: 'sneaker-white', alt: 'Pair of white knit sneakers with white laces, seen from above'),
      ProductImage(base: 'sneaker-white-detail', alt: 'Close-up of the knit upper and laces of the white sneakers'),
    ],
    variants: const [
      ProductVariant(id: 'v_stride_40', label: '40', sku: 'NG-SNK-001-40', stock: 6),
      ProductVariant(id: 'v_stride_41', label: '41', sku: 'NG-SNK-001-41', stock: 9),
      ProductVariant(id: 'v_stride_42', label: '42', sku: 'NG-SNK-001-42', stock: 12),
      ProductVariant(id: 'v_stride_43', label: '43', sku: 'NG-SNK-001-43', stock: 7),
      ProductVariant(id: 'v_stride_44', label: '44', sku: 'NG-SNK-001-44', stock: 0),
      ProductVariant(id: 'v_stride_45', label: '45', sku: 'NG-SNK-001-45', stock: 3),
    ],
    details: const [
      ProductDetail('Materials', 'Upper: 100% recycled polyester knit. Midsole: EVA foam. Outsole: natural rubber.'),
      ProductDetail('Fit & sizing', 'True to size. If you are between sizes, we recommend sizing up.'),
      ProductDetail('Care', 'Machine wash cold in a laundry bag. Air dry away from direct heat.'),
      ProductDetail('Shipping & returns', 'Free standard shipping over \$75. Free returns within 30 days, unworn.'),
    ],
    tags: const ['sneakers', 'knit', 'lightweight', 'everyday', 'vegan'],
    featured: true,
    createdAt: DateTime.utc(2025, 9, 12),
    updatedAt: DateTime.utc(2026, 2, 20),
  ),
  Product(
    id: 'p_court_low',
    slug: 'court-low-sneaker',
    name: 'Court Low Sneaker',
    brand: 'Northgate',
    categorySlug: 'footwear',
    summary: 'A low-profile black mesh sneaker on a white sole, with contrast laces.',
    description: [
      'Court Low pairs a breathable black mesh upper with a bright white cupsole. It is the sneaker that works with jeans, chinos and a suit trouser.',
      'The heel is padded and the lacing is tonal, so the shoe looks as good on day 200 as on day one.',
    ],
    priceCents: 8900,
    sku: 'NG-SNK-002',
    gtin: '8401234510075',
    variantLabel: 'Size (EU)',
    images: const [
      ProductImage(
        base: 'sneaker-black',
        alt: 'Heel of a black mesh sneaker on a white sole with navy and green laces',
      ),
    ],
    variants: const [
      ProductVariant(id: 'v_court_41', label: '41', sku: 'NG-SNK-002-41', stock: 4),
      ProductVariant(id: 'v_court_42', label: '42', sku: 'NG-SNK-002-42', stock: 8),
      ProductVariant(id: 'v_court_43', label: '43', sku: 'NG-SNK-002-43', stock: 8),
      ProductVariant(id: 'v_court_44', label: '44', sku: 'NG-SNK-002-44', stock: 5),
    ],
    details: const [
      ProductDetail('Materials', 'Upper: breathable mesh. Lining: recycled textile. Sole: vulcanised rubber.'),
      ProductDetail('Fit & sizing', 'Regular fit. Order your usual size.'),
      ProductDetail('Care', 'Wipe clean with a damp cloth. Do not tumble dry.'),
    ],
    tags: const ['sneakers', 'mesh', 'black', 'everyday'],
    createdAt: DateTime.utc(2025, 10, 3),
    updatedAt: DateTime.utc(2026, 1, 15),
  ),
  Product(
    id: 'p_halo_wireless',
    slug: 'halo-wireless-headphones',
    name: 'Halo Wireless On-Ear Headphones',
    brand: 'Northgate Audio',
    categorySlug: 'audio',
    summary: 'Bluetooth on-ear headphones with 40 hours of battery and a soft, folding design.',
    description: [
      'Halo is built for long days. The memory-foam ear cushions are light on the ears, and the folding arms slide flat into a bag.',
      'Bluetooth 5.3 keeps the connection steady, and a built-in microphone handles calls. Forty hours of playback means you charge them on Sundays.',
    ],
    priceCents: 12900,
    sku: 'NG-AUD-001',
    gtin: '8401234510143',
    variantLabel: 'Colour',
    images: const [
      ProductImage(base: 'headphones-white', alt: 'White wireless on-ear headphones on a white background'),
    ],
    variants: const [
      ProductVariant(id: 'v_halo_white', label: 'Cloud white', sku: 'NG-AUD-001-WHT', stock: 14),
      ProductVariant(id: 'v_halo_sand', label: 'Sand', sku: 'NG-AUD-001-SND', stock: 0),
    ],
    details: const [
      ProductDetail('Specifications', 'Bluetooth 5.3, 40 mm drivers, 40 hours playback, USB-C charging, 255 g.'),
      ProductDetail('In the box', 'Headphones, USB-C cable, carry pouch, quick-start guide.'),
      ProductDetail('Warranty', 'Two-year limited warranty against manufacturing defects.'),
    ],
    tags: const ['headphones', 'wireless', 'bluetooth', 'on-ear'],
    featured: true,
    createdAt: DateTime.utc(2025, 11, 1),
    updatedAt: DateTime.utc(2026, 2, 2),
  ),
  Product(
    id: 'p_studio_wired',
    slug: 'studio-wired-headphones',
    name: 'Studio Wired Headphones',
    brand: 'Northgate Audio',
    categorySlug: 'audio',
    summary: 'Closed-back wired headphones with brushed metal cups and a bold low end.',
    description: [
      'A pair of wired headphones that is easy to love: brushed aluminium-look cups, a flat tangle-resistant cable and plenty of bass without muddying the vocals.',
      'No battery, no pairing, no latency. Plug them into anything with a 3.5 mm jack.',
    ],
    priceCents: 5900,
    compareAtCents: 7900,
    sku: 'NG-AUD-002',
    gtin: '8401234510211',
    variantLabel: 'Colour',
    images: const [
      ProductImage(base: 'headphones-pink', alt: 'Silver wired headphones laid flat on a pink background'),
      ProductImage(base: 'headphones-pink-detail', alt: 'Close-up of the brushed metal ear cups'),
    ],
    variants: const [
      ProductVariant(id: 'v_studio_silver', label: 'Silver', sku: 'NG-AUD-002-SLV', stock: 5),
    ],
    details: const [
      ProductDetail('Specifications', '40 mm drivers, 20 Hz-20 kHz, 32 ohm, 1.2 m flat cable, 3.5 mm plug.'),
      ProductDetail('Warranty', 'One-year limited warranty.'),
    ],
    tags: const ['headphones', 'wired', 'closed-back', 'bass'],
    createdAt: DateTime.utc(2025, 8, 20),
    updatedAt: DateTime.utc(2026, 1, 8),
  ),
  Product(
    id: 'p_classic_38',
    slug: 'classic-38-watch',
    name: 'Classic 38 Watch',
    brand: 'Northgate',
    categorySlug: 'accessories',
    summary: 'A 38 mm minimalist watch with a white dial, rose-gold indices and a leather strap.',
    description: [
      'Classic 38 is a three-hand quartz watch designed to disappear on the wrist. The dial is matte white with slim rose-gold indices and no date window to clutter it.',
      'The strap is vegetable-tanned leather with quick-release spring bars, so changing it takes seconds.',
    ],
    priceCents: 14900,
    sku: 'NG-WCH-001',
    gtin: '8401234510280',
    variantLabel: 'Strap',
    images: const [
      ProductImage(
        base: 'watch-classic',
        alt: 'Minimalist wristwatch with white dial and brown leather strap on a wooden table',
      ),
      ProductImage(base: 'watch-classic-detail', alt: 'Three-quarter view of the white dial and rose-gold hands'),
    ],
    variants: const [
      ProductVariant(id: 'v_classic_brown', label: 'Brown leather', sku: 'NG-WCH-001-BRN', stock: 8),
      ProductVariant(id: 'v_classic_black', label: 'Black leather', sku: 'NG-WCH-001-BLK', stock: 3),
    ],
    details: const [
      ProductDetail(
        'Specifications',
        '38 mm stainless steel case, mineral crystal, Japanese quartz movement, 3 ATM water resistance.',
      ),
      ProductDetail('Strap', '18 mm vegetable-tanned leather, quick-release.'),
      ProductDetail('Warranty', 'Two-year movement warranty.'),
    ],
    tags: const ['watch', 'minimalist', 'leather', 'gift'],
    featured: true,
    previousSlugs: const ['classic-watch'],
    createdAt: DateTime.utc(2025, 6, 5),
    updatedAt: DateTime.utc(2026, 2, 27),
  ),
  Product(
    id: 'p_skeleton_sport',
    slug: 'skeleton-sport-watch',
    name: 'Skeleton Sport Watch',
    brand: 'Northgate',
    categorySlug: 'accessories',
    summary: 'A statement automatic watch with an open dial and a wheel-inspired movement.',
    description: [
      'The Skeleton Sport shows its work. An open dial reveals the rotor, and the wheel-spoke pattern gives the watch a mechanical, motorsport feel.',
      'It is a limited run: when the current batch is gone, it is gone.',
    ],
    priceCents: 18900,
    sku: 'NG-WCH-002',
    gtin: '8401234510358',
    variantLabel: 'Case',
    images: const [
      ProductImage(
        base: 'watch-sport',
        alt: 'Skeleton-dial sport watch with a red and silver wheel pattern worn on a wrist',
      ),
    ],
    variants: const [ProductVariant(id: 'v_skeleton_42', label: '42 mm', sku: 'NG-WCH-002-42', stock: 2)],
    details: const [
      ProductDetail('Specifications', '42 mm case, automatic movement, 38-hour power reserve, 5 ATM.'),
      ProductDetail('Warranty', 'Two-year limited warranty.'),
    ],
    tags: const ['watch', 'automatic', 'sport', 'limited'],
    createdAt: DateTime.utc(2026, 1, 20),
    updatedAt: DateTime.utc(2026, 2, 28),
  ),
  Product(
    id: 'p_round_sunglasses',
    slug: 'round-sunglasses',
    name: 'Round Sunglasses',
    brand: 'Northgate',
    categorySlug: 'accessories',
    summary: 'Lightweight round sunglasses with UV400 lenses and a slim metal frame.',
    description: [
      'A classic round shape in a frame that weighs almost nothing. The lenses block 100% of UVA and UVB, and the spring hinges adjust to most face shapes.',
      'Choose a tortoiseshell or rose-tinted lens. A soft case is included.',
    ],
    priceCents: 6800,
    sku: 'NG-EYE-001',
    gtin: '8401234510426',
    variantLabel: 'Lens',
    images: const [
      ProductImage(base: 'sunglasses', alt: 'Three pairs of sunglasses and glasses arranged on a cream surface'),
    ],
    variants: const [
      ProductVariant(id: 'v_round_tort', label: 'Tortoise', sku: 'NG-EYE-001-TRT', stock: 11),
      ProductVariant(id: 'v_round_rose', label: 'Rose', sku: 'NG-EYE-001-RSE', stock: 6),
    ],
    details: const [
      ProductDetail('Specifications', 'UV400 lenses, metal frame, 142 mm width, 24 g.'),
      ProductDetail('Included', 'Soft case and cleaning cloth.'),
    ],
    tags: const ['sunglasses', 'eyewear', 'uv400', 'summer'],
    createdAt: DateTime.utc(2025, 12, 5),
    updatedAt: DateTime.utc(2026, 2, 10),
  ),
  Product(
    id: 'p_weekender_duffel',
    slug: 'weekender-leather-duffel',
    name: 'Weekender Leather Duffel',
    brand: 'Northgate',
    categorySlug: 'bags',
    summary: 'A full-grain leather duffel sized for a long weekend, and made to be repaired.',
    description: [
      'The Weekender is cut from full-grain leather that darkens and softens as it ages. Two rolled handles and a removable strap make it comfortable to carry any way you like.',
      'The zip, hardware and stitching are all replaceable. Send it back in ten years and we will refurbish it.',
    ],
    priceCents: 24000,
    sku: 'NG-BAG-001',
    gtin: '8401234510495',
    variantLabel: 'Colour',
    images: const [ProductImage(base: 'duffel', alt: 'Brown leather duffel bag on a dark tiled floor')],
    variants: const [ProductVariant(id: 'v_duffel_tan', label: 'Tan', sku: 'NG-BAG-001-TAN', stock: 4)],
    details: const [
      ProductDetail('Dimensions', '52 x 28 x 26 cm, 38 litres, 1.6 kg.'),
      ProductDetail('Materials', 'Full-grain vegetable-tanned leather, brass hardware, cotton lining.'),
      ProductDetail('Care', 'Condition twice a year with a leather balm.'),
    ],
    tags: const ['bag', 'duffel', 'leather', 'travel'],
    featured: true,
    createdAt: DateTime.utc(2025, 5, 14),
    updatedAt: DateTime.utc(2026, 1, 30),
  ),
  Product(
    id: 'p_courier_satchel',
    slug: 'courier-leather-satchel',
    name: 'Courier Leather Satchel',
    brand: 'Northgate',
    categorySlug: 'bags',
    summary: 'A structured satchel with a padded laptop sleeve and brass buckles.',
    description: [
      'A satchel for people who still carry paper. The structured body holds its shape, and a padded sleeve fits a 14-inch laptop.',
      'Two buckled straps close the flap; a hidden zip pocket keeps your passport and keys out of reach.',
    ],
    priceCents: 17500,
    sku: 'NG-BAG-002',
    gtin: '8401234510563',
    variantLabel: 'Colour',
    images: const [ProductImage(base: 'satchel', alt: 'Tan and black leather satchels lined up against a pale wall')],
    variants: const [
      ProductVariant(id: 'v_satchel_tan', label: 'Tan', sku: 'NG-BAG-002-TAN', stock: 7),
      ProductVariant(id: 'v_satchel_black', label: 'Black', sku: 'NG-BAG-002-BLK', stock: 5),
    ],
    details: const [
      ProductDetail('Dimensions', '38 x 28 x 10 cm, 14 litres, 1.1 kg.'),
      ProductDetail('Materials', 'Full-grain leather, brass buckles, recycled-cotton lining.'),
    ],
    tags: const ['bag', 'satchel', 'leather', 'laptop', 'work'],
    createdAt: DateTime.utc(2025, 7, 18),
    updatedAt: DateTime.utc(2026, 2, 1),
  ),
  Product(
    id: 'p_day_backpack',
    slug: 'day-backpack',
    name: 'Day Backpack',
    brand: 'Northgate',
    categorySlug: 'bags',
    summary: 'A water-resistant 20 litre backpack with a padded laptop sleeve.',
    description: [
      'Day is the backpack we use ourselves. A water-resistant recycled canvas shell, a roomy main compartment and a front pocket that is big enough for a charger and a notebook.',
      'Padded straps and a ventilated back panel keep it comfortable on the long walk.',
    ],
    priceCents: 8500,
    compareAtCents: 9900,
    sku: 'NG-BAG-003',
    gtin: '8401234510631',
    variantLabel: 'Colour',
    images: const [
      ProductImage(base: 'backpack', alt: 'A black backpack held up by one hand against a white wall'),
      ProductImage(base: 'backpack-detail', alt: 'Close-up of the front pocket of the black backpack'),
    ],
    variants: const [ProductVariant(id: 'v_day_black', label: 'Black', sku: 'NG-BAG-003-BLK', stock: 22)],
    details: const [
      ProductDetail('Dimensions', '45 x 30 x 15 cm, 20 litres, 0.8 kg.'),
      ProductDetail('Materials', 'Recycled canvas with a PFC-free water-repellent finish.'),
    ],
    tags: const ['bag', 'backpack', 'canvas', 'commute', 'laptop'],
    featured: true,
    createdAt: DateTime.utc(2025, 4, 2),
    updatedAt: DateTime.utc(2026, 2, 18),
  ),
  Product(
    id: 'p_stoneware_mug',
    slug: 'stoneware-mug',
    name: 'Stoneware Mug',
    brand: 'Northgate Home',
    categorySlug: 'home',
    summary: 'A 350 ml stoneware mug with a generous handle and a matte glaze.',
    description: [
      'A mug you reach for every morning. Thick-walled stoneware keeps drinks hot, and the generous handle fits two fingers comfortably.',
      'Dishwasher and microwave safe. Sold individually or build a set.',
    ],
    priceCents: 2200,
    sku: 'NG-HOM-001',
    gtin: '8401234510709',
    variantLabel: 'Glaze',
    images: const [ProductImage(base: 'mug', alt: 'A plain white stoneware mug on a pale table')],
    variants: const [ProductVariant(id: 'v_mug_white', label: 'Chalk white', sku: 'NG-HOM-001-WHT', stock: 40)],
    details: const [
      ProductDetail('Dimensions', 'Holds 350 ml. 9 cm tall, 8 cm wide.'),
      ProductDetail('Care', 'Dishwasher and microwave safe.'),
    ],
    tags: const ['mug', 'kitchen', 'stoneware', 'gift'],
    createdAt: DateTime.utc(2025, 3, 8),
    updatedAt: DateTime.utc(2026, 1, 4),
  ),
  Product(
    id: 'p_desk_notebook',
    slug: 'lay-flat-notebook',
    name: 'Lay-Flat Notebook',
    brand: 'Northgate Home',
    categorySlug: 'home',
    summary: 'A thread-bound dot-grid notebook that opens fully flat.',
    description: [
      'A notebook that behaves. The thread binding lets it open completely flat, and 120 gsm paper takes fountain pen ink without ghosting.',
      '192 numbered pages with a dot grid, a ribbon bookmark and an index at the front.',
    ],
    priceCents: 1800,
    sku: 'NG-HOM-002',
    gtin: '8401234510778',
    variantLabel: 'Ruling',
    images: const [ProductImage(base: 'notebook', alt: 'Open dot-grid notebook with a black pen on a pine desk')],
    variants: const [
      ProductVariant(id: 'v_notebook_dot', label: 'Dot grid', sku: 'NG-HOM-002-DOT', stock: 30),
      ProductVariant(id: 'v_notebook_ruled', label: 'Ruled', sku: 'NG-HOM-002-RUL', stock: 18),
    ],
    details: const [
      ProductDetail('Specifications', 'A5, 192 pages, 120 gsm acid-free paper, thread-bound.'),
    ],
    tags: const ['notebook', 'stationery', 'desk', 'gift'],
    createdAt: _t,
    updatedAt: DateTime.utc(2026, 3, 1),
  ),
];
