/// DEMO STAND-IN. Seed reviews, keyed by product id.
library;

import '../domain/reviews/models/review.dart';

Review _r(
  String id,
  String product,
  String author,
  int rating,
  String title,
  String body,
  DateTime date, {
  bool verified = true,
}) => Review(
  id: id,
  productId: product,
  author: author,
  rating: rating,
  title: title,
  body: body,
  date: date,
  verified: verified,
);

List<Review> seedReviews() => [
  _r(
    'r1',
    'p_stride_knit',
    'Maya R.',
    5,
    'Genuinely light',
    'I wore these for a 12 hour travel day and forgot they were on. No break-in at all.',
    DateTime.utc(2026, 1, 14),
  ),
  _r(
    'r2',
    'p_stride_knit',
    'Tomas K.',
    4,
    'Great, but runs a bit narrow',
    'Lovely shoe. If you have wide feet, size up half a size.',
    DateTime.utc(2025, 12, 2),
  ),
  _r(
    'r3',
    'p_stride_knit',
    'Priya S.',
    5,
    'My new default',
    'Plain, comfortable and they survived the washing machine.',
    DateTime.utc(2025, 11, 18),
  ),
  _r(
    'r4',
    'p_stride_knit',
    'Jon A.',
    5,
    'Worth it on sale',
    'Bought two pairs. Would buy a third.',
    DateTime.utc(2026, 2, 3),
  ),
  _r(
    'r5',
    'p_court_low',
    'Leah W.',
    4,
    'Smart and comfy',
    'Works with suit trousers and jeans. The laces are a nice touch.',
    DateTime.utc(2026, 1, 9),
  ),
  _r(
    'r6',
    'p_court_low',
    'Dan P.',
    5,
    'Great value',
    'Better than sneakers twice the price.',
    DateTime.utc(2025, 12, 20),
  ),
  _r(
    'r7',
    'p_court_low',
    'Ines F.',
    3,
    'Good, slightly stiff',
    'Took a week to soften up around the heel.',
    DateTime.utc(2025, 11, 5),
    verified: false,
  ),
  _r(
    'r8',
    'p_halo_wireless',
    'Chris M.',
    5,
    'Battery for days',
    'Used them all week at the office and only charged them on Sunday.',
    DateTime.utc(2026, 2, 8),
  ),
  _r(
    'r9',
    'p_halo_wireless',
    'Aiko T.',
    4,
    'Comfortable and clear',
    'Calls are crisp and the cushions are soft. Bass is modest.',
    DateTime.utc(2026, 1, 22),
  ),
  _r(
    'r10',
    'p_halo_wireless',
    'Sam L.',
    5,
    'Folds flat',
    'Fits in my jacket pocket. Sound is clean.',
    DateTime.utc(2025, 12, 15),
  ),
  _r(
    'r11',
    'p_studio_wired',
    'Noor H.',
    5,
    'Punchy for the price',
    'Plug in and go. The cable is surprisingly tough.',
    DateTime.utc(2026, 1, 11),
  ),
  _r(
    'r12',
    'p_studio_wired',
    'Ben D.',
    4,
    'Fun sound',
    'Bass-forward but not boomy. Would love a coiled cable option.',
    DateTime.utc(2025, 12, 8),
  ),
  _r(
    'r13',
    'p_classic_38',
    'Olivia N.',
    5,
    'Gift she loved',
    'Bought it as a gift, she hasn\'t taken it off in a month.',
    DateTime.utc(2026, 2, 14),
  ),
  _r(
    'r14',
    'p_classic_38',
    'Marcus E.',
    5,
    'Quietly beautiful',
    'The dial is lovely in person. Swapped the strap in ten seconds.',
    DateTime.utc(2026, 1, 3),
  ),
  _r(
    'r15',
    'p_classic_38',
    'Zoe B.',
    4,
    'Smaller than expected',
    '38 mm sounds big but wears small. Looks great on a slim wrist.',
    DateTime.utc(2025, 11, 27),
  ),
  _r(
    'r16',
    'p_classic_38',
    'Ravi G.',
    5,
    'Accurate and simple',
    'Gains about a second a week. Perfect.',
    DateTime.utc(2025, 10, 9),
  ),
  _r(
    'r17',
    'p_skeleton_sport',
    'Hugo C.',
    5,
    'A conversation piece',
    'People ask about it every day. Smooth sweep.',
    DateTime.utc(2026, 2, 21),
  ),
  _r('r18', 'p_skeleton_sport', 'Dana V.', 4, 'Bold', 'Looks great, a little large for me.', DateTime.utc(2026, 2, 12)),
  _r(
    'r19',
    'p_round_sunglasses',
    'Elena J.',
    5,
    'Light as air',
    'Can wear them all day without a headache.',
    DateTime.utc(2026, 1, 30),
  ),
  _r(
    'r20',
    'p_round_sunglasses',
    'Pete O.',
    4,
    'Good lenses',
    'Sharp and glare-free. Case is a nice extra.',
    DateTime.utc(2026, 1, 6),
  ),
  _r(
    'r21',
    'p_weekender_duffel',
    'Frances Q.',
    5,
    'Heirloom quality',
    'Took it on a three week trip. Already developing a patina.',
    DateTime.utc(2026, 2, 6),
  ),
  _r(
    'r22',
    'p_weekender_duffel',
    'Karl Z.',
    5,
    'Roomy',
    'Fits a surprising amount. The strap is excellent.',
    DateTime.utc(2025, 12, 28),
  ),
  _r(
    'r23',
    'p_weekender_duffel',
    'Mia Y.',
    4,
    'Heavy empty',
    'Leather is thick. Worth it, but it is no featherweight.',
    DateTime.utc(2025, 11, 11),
  ),
  _r(
    'r24',
    'p_courier_satchel',
    'Omar X.',
    5,
    'Laptop and notebooks',
    'Fits everything and looks good doing it.',
    DateTime.utc(2026, 1, 19),
  ),
  _r(
    'r25',
    'p_courier_satchel',
    'Hana U.',
    4,
    'Stiff at first',
    'Softened up after a few weeks.',
    DateTime.utc(2025, 12, 12),
  ),
  _r(
    'r26',
    'p_day_backpack',
    'Theo I.',
    5,
    'The one',
    'Has survived a rainy month of commuting.',
    DateTime.utc(2026, 2, 16),
  ),
  _r(
    'r27',
    'p_day_backpack',
    'Rosa Q.',
    4,
    'Sensible',
    'Nothing fancy, everything works. A second front pocket would be perfect.',
    DateTime.utc(2026, 1, 25),
  ),
  _r(
    'r28',
    'p_day_backpack',
    'Walt M.',
    5,
    'Comfortable straps',
    'Carried it for a week of walking tours.',
    DateTime.utc(2025, 12, 1),
  ),
  _r('r29', 'p_stoneware_mug', 'Gia F.', 5, 'Perfect mug', 'Keeps tea warm for ages.', DateTime.utc(2026, 1, 12)),
  _r(
    'r30',
    'p_stoneware_mug',
    'Luis P.',
    5,
    'Solid',
    'Feels premium for the price. Bought four.',
    DateTime.utc(2025, 12, 5),
  ),
  _r(
    'r31',
    'p_desk_notebook',
    'Ada B.',
    5,
    'Lies flat',
    'Finally a notebook I can write in without holding it open.',
    DateTime.utc(2026, 2, 19),
  ),
];
